######################################################
################## Setup Suricata ####################
######################################################
---

- name: "Setup ROCK NSM repo"
  yum_repository:
    baseurl: "{{ rocknsm_baseurl }}"
    cost: 750
    description: "ROCK NSM repository for devel"
    gpgcheck: false
    gpgkey: "{{ rocknsm_gpgurl }}"
    name: rocknsm
    
- name: Install Suricata package
  yum:
    name: suricata
    state: installed

- name: Create the confd directory
  file:
    path: "{{ confd_directory }}"
    mode: 0755
    owner: "{{ suricata_user }}"
    group: "{{ suricata_group }}"
    state: directory

- name: Create the confd templates directory
  file:
    path: "{{ confd_templates }}"
    mode: 0755
    owner: "{{ suricata_user }}"
    group: "{{ suricata_group }}"
    state: directory

- name: Create Suricata directories
  file:
    path: "/data/suricata"
    mode: 0755
    owner: "{{ suricata_user }}"
    group: "{{ suricata_group }}"
    state: directory

# This is required so that the filebeat container can actually read this data
# TODO: Make sure this is correct
- name: Change permissions of Suricata log directory
  file:
    path: "/var/log/suricata"
    mode: 0755
    owner: "{{ suricata_user }}"
    group: "{{ suricata_group }}"
    state: directory

- name: Copy Suricata configuration toml file
  copy:
    src: "suricata.yaml.toml"
    dest: "{{ confd_directory }}/suricata.yaml.toml"
    mode: 0644
    owner: root
    group: root

- name: Copy Suricata configuration template file
  copy:
    src: "suricata.yaml.tmpl"
    dest: "{{ confd_templates }}/suricata.yaml.tmpl"
    mode: 0644
    owner: root
    group: root

- name: Copy Suricata logrotate toml file
  copy:
    src: "logrotate-suricata.conf.toml"
    dest: "{{ confd_directory }}/logrotate-suricata.conf.toml"
    mode: 0644
    owner: root
    group: root

- name: Copy Suricata logrotate template file
  copy:
    src: "logrotate-suricata.conf.tmpl"
    dest: "{{ confd_templates }}/logrotate-suricata.conf.tmpl"
    mode: 0644
    owner: root
    group: root

- name: Set suricata capabilities
  capabilities:
    path: /usr/sbin/suricata
    capability: "{{ item }}"
    state: present
  with_items:
    - "cap_net_raw+eip"
    - "cap_net_admin+eip"
    - "cap_ipc_lock+eip"

- name: Remove suricata sysconfig file
  file:
    path: /etc/sysconfig/suricata
    state: absent

- name: Install suricata service files
  copy:
    src: "suricata.service"
    dest: "/etc/systemd/system/suricata.service"
    mode: 0644
    owner: root
    group: root

- name: Create IP reputation config dir
  file:
    path: /etc/suricata/rules/iplists
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Configure Suricata /var directory permissions
  file:
    path: /var/run/suricata
    owner: suricata
    group: suricata
    mode: 755

- name: Enable and start suricata
  systemd:
    name: suricata
    enabled: yes
    state: started
    daemon_reload: yes
